### ISSUE TITLE
Remove unused vars in destructuring assignments

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#114]
```js
// Before.
function foo() {
  const [$bar, $buzz] = qux();
  return $buzz;
}

// After
function foo() {
  const [, $buzz] = qux();
  return $buzz;
}
```

**Comment by lemonmade** [comment]
Do we have many of these? To me, this seems quite challenging because we need to check whether a given variable is used, which could happen in many different ways. I also am not a huge fan of the extra commas thing to get at the parts of an array you want, even though I understand why it is sometimes useful.

**Comment by GoodForOneFare** [comment]
Yep, I'd say there <5, and this seems like a lot of effort for something that's easy to manually fix after the transforms are done.
