### ISSUE TITLE
Question RE space-before-function-paren

### ISSUE THREAD

**Issue by nathanmarks** [Shopify/javascript#216]
In the styleguide it mentions that we use `space-before-function-paren` to prevent anonymous functions having a space before the parens for consistency.

However, since a named function is like:

```js
function doSomething() {}
```

Wouldn't it be more consistent to leave a space between `function` and `()` for anonymous functions since there is a space between `function` and `doSomething`, with `function` having nothing to do with the naming part? 

```js
const doSomething = function () {};
```

**Comment by lemonmade** [comment]
So, I think this is mostly not a problem since we:

- Encourage function declarations over expressions, and
- Encourage arrow functions for callbacks

After that, it's mostly a matter of preference, and IMO the `function() {}` version is preferable since it keeps parens consistently without a left space for all forms of function, and consistently with a space for all control flow (`if () {}`, etc).

**Comment by nathanmarks** [comment]
@lemonmade 

I'm happy with it if everyone else is 👍  

Just for some context, I'm starting to work on bringing the marketing projects JS up to date with our centralized styleguide/config. It'd be great to have things aligned across the org so we can reduce developer friction and maintenance load. Looking forward to getting es6 going on the marketing projects too -- I'm missing it terribly 😹
