### ISSUE TITLE
Why prefer js file extension over jsx?

### ISSUE THREAD

**Issue by ihsw** [Shopify/javascript#31]
Surely the file is not valid JS so it would be prudent to use jsx.

**Comment by lemonmade** [comment]
"Valid" JS is a tricky distinction to make — are features that have not yet made their way into the spec not "valid"? Should there be a separate extension for files that use those features? Are files using flow typing not "valid"? Should there be a separate extension for those, too?

From our perspective, it is simpler from a tooling and discussion perspective to refer to all features, standard and non-standard, used in a project as "JavaScript", and to use the `.js` extension for all of them. This also reduces complexity for tooling, since you don't have to ensure that things like `.jsx` and `.es6` are resolvable, and you never have to change the file extension as you add potentially non-standard features to a given file.

From what I've seen, the community and the React project itself stick to `.js` everywhere, so this doesn't appear to be a particularly contentious issue.
